version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql:delegated
      - ./db/mysql.cnf:/etc/mysql/conf.d/my.cnf

